version: '3'
services:
  ello-postgres-development:
    image: postgres:14
    container_name: ello-postgres-development
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ello-postgres-data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
  ello-development:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: ello-development
    depends_on:
      - ello-postgres-development
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    working_dir: /usr/src/ello
    command: bash -c "npx prisma generate && npm run dev"
    environment:
      NODE_ENV: development
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./src:/usr/src/ello/src
      - ./prisma:/usr/src/ello/prisma
      - ./.env.development:/usr/src/ello/.env.development
      - ./.eslintrc.js:/usr/src/ello/.eslintrc.js
      - ./.eslintignore:/usr/src/ello/.eslintignore
      - ./.prettierrc.js:/usr/src/ello/.prettierrc.js
      - ./tsconfig.json:/usr/src/ello/tsconfig.json
    ports:
      - "5000:5000"
volumes:
  ello-postgres-data: